namespace NumberOfActiveDisplays.NativeInterop.Types
{
    enum DISPLAYCONFIG_VIDEO_SIGNAL_INFO_VIDEOSTANDARD : uint
    {
        UNINITIALIZED = 0,
        VESA_DMT = 1,
        VESA_GTF = 2,
        VESA_CVT = 3,
        IBM = 4,
        APPLE = 5,
        NTSC_M = 6,
        NTSC_J = 7,
        NTSC_443 = 8,
        PAL_B = 9,
        PAL_B1 = 10,
        PAL_G = 11,
        PAL_H = 12,
        PAL_I = 13,
        PAL_D = 14,
        PAL_N = 15,
        PAL_NC = 16,
        SECAM_B = 17,
        SECAM_D = 18,
        SECAM_G = 19,
        SECAM_H = 20,
        SECAM_K = 21,
        SECAM_K1 = 22,
        SECAM_L = 23,
        SECAM_L1 = 24,
        EIA_861 = 25,
        EIA_861A = 26,
        EIA_861B = 27,
        PAL_K = 28,
        PAL_K1 = 29,
        PAL_L = 30,
        PAL_M = 31,
        OTHER = 255,
    }
}
